language: node_js
node_js:
  - lts/*
  - node
install:
  - npm ci
script:
  - npm run test:ci
  - npm run build
deploy:
  provider: npm
  email: bhargav@dkinom.dev
  api_key:
    secure: gO16LZEKp2l1v3PU8L+eMaTr1l7kdvOn6Dc0RItRs5Dns8UVSqUZZ7c96rAWg1yO+UoeHhTshxlMe0fagMm9c82Q43PEWq4NfSY8NVkVWOsDPYqk9vjLdFtOf2ePQjM/yZprjQXdZ1KJZhQllsDEkTBhqocmwANeWAfY7eHHOfSPv1/bRqyIdRNst0aqW79qRSRv/siYfn6kzuJL3j4nl3Tx2FFxB4iTMSvIdGCc5G7jYqky8opc/s0R29pAULaelf7fT7IxzDvagkGkcyXpnY/FJj+d0h0eIjL29wIil5TF6z7DbvnilOgNtg6esONsu2LiQD8awdFoMytVSyO6mFE7q4FF6jL9gsJOMS2ZtppAvEq0VhuUJhLAHG3FiXjSV77NRFv4kTwH6SLRwtihRZSMK2w7sL63WqliUmZvBcZa9IhuUXAjxBGrnEvbLlQPMCOqwuWCtGkzNrQRNRoSUI7hi6TvwTet051opzjZgYlTk15shkfneqXR8Oe2ed5ZxvyuXxNGuQx4wXWvWi6YMzADez6wARz819PDU02iq1Mkof5eV1S5UqBCGSYaFg1dDow/SkgkB9QkfWOKEHydI+CWD+5VbjEg9zmXWmO7GkbRYs+STb6KuaqoaOVlq+ZgpmL9ebIg/nwAk9fRsk2j6JUCfFNxe0s7NVdCdu9eCcA=
  on:
    node_js: lts/*
    tags: true
    repo: dkin-om/romanice
  skip_cleanup: true
