language: node_js
node_js:
  - '10'
  - '12'
  - '14'
install:
  - npm ci
script:
  - npm run test:ci
  - npm run build
deploy:
  provider: npm
  email: bhargav@dkinom.dev
  api_key:
    secure: OD6C4ScqfN6PPxjjUH5R2zUeJ1/oZ69bZ+0iHsG0NJbZ9+w8kIWJOW6k96ro1DjQwyhkm+p9uvfYTz2Ph6muW1fgyBbyZkoLGic41npS58aO1kiRsxtQx27TymErxmpBLiymR/Ne2Hj4IVZn6eIDSDwKLdt2vM2s5fS1l74XO+0XC77gZ6kSB6pD5hsMmY756QWOcjf1ZyPv/4gk0Ys9Ax9rlDPYIyzWGi2WLJeQrofi6itaPTHEuXbi8gp/cr8UNvJW4b6QPOjJTOV7xlhArh+zNN2nBkiRxvnhIjC79V48IizmKX2clK7F6S5SjdPM8uWge17WVFYKoiw7FUwoLScOx9GDGRw9F4LZpoV28RqsxSGLI4Jrs3AF2n+89B+QrcQ1dMHnwZCJkHIsPifYltsfWvocBSlyyLbEDPFWsHAhKik8DSoPTqUatsTU/Sx8FVyGaAWD/j9tBceklWkJBcGJI6StXioC4MpVEGpV5C8/L3VDHop5mUDJuVl8/5E/bdpR6RXzK4ze0+yPbAR01HQOOpy3BFATBPi+PpSQUIQDIJQIsn4XJu5uAotvahHGOCMu6SrBX4q+Rv5EVgG0UmpZSkdez3yWM16OkWSJtHcw6SM8TShW8gxf+YqFxYhXXOjIDDDrR5EzhC/DXjkcdckZCiLrqXt7Bw19V38UhpY=
  on:
    node_js: '12'
    tags: true
    repo: dkin-om/romanice
  skip_cleanup: true
